### ISSUE TITLE
"Bad data" trimming tool for nodes needed

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#8]
If you look at the phone number 3477971823 in tellfinder you will see that it returns an incredibly large network. A large portion of this network is composed of valuable connections, unfortunately a large number of the linkages made by this graph are also from bad phone number extractions, as such to discern between what connections are valid and invalid you need to go through and manually vet each number to make sure it is a valid connection, which turns a 5-10 minute copy and paste process into a 4 hour time sink for just that one phone number.
It is strongly desired to have an in tool way to denote a phone number, email address, or website as being a bad extraction and have it and its connections removed from the observed node.

**Comment by eric-oculus** [comment]
We have this capability but it is time consuming and dangerous. A better fix is a major redesign with user-specific clustering and editing but this solution will not be available near term.

A more short term solution might be looking at using the Stanford-NER in the pipeline since they are claiming solid numbers for phone extraction.
